---
title: "Presentation-Rcode"
author: "Mehdi Nojoumi"
date: "March 12, 2017"
output: md_document
---


1-Making tree of representative species
```{r}
#install.packages("devtools")
#install.packages("phytools")
#install.packages("psych")
#install.packages("ape")
#install.packages("geiger")

library(devtools)
library(psych)
library(ape)
library(phytools)
library(geiger)
library(phytools)

#all species of non-occurance
nooccuranceallspecies<-read.csv("/home/eeb177-student/Desktop/eeb-177/eeb-174-final-project/Presentation/non_occurance_reps.csv", header = TRUE)

#for reading the tree
complete.tree<-read.tree(file="/home/eeb177-student/Desktop/eeb-177/eeb-174-final-project/Presentation/Hackett_Stage2_1K_MCCtree_TargetHeights.tre")

#openning occurance species csv file
occurancespecies<-read.csv("/home/eeb177-student/Desktop/eeb-177/eeb-174-final-project/Presentation/bird_occurance_reps.csv", header = TRUE)

taxa_to_drop=("")
i<-1
for (j in nooccuranceallspecies$Species){
  taxa_to_drop[[i]]<-j
  i=i+1
  }

#for removing the unwanted tips
simple.tree<-drop.tip(complete.tree,taxa_to_drop)

#setting discrete variable as a factor:
x<-setNames(occurancespecies$Occurance,occurancespecies$Species)

#  model with the backward & forward rates between states are permitted to have different values
fitARD<-ace(x,simple.tree,model="ARD",type="discrete")
fitARD

#plotting ARD model on the tree

cols<-setNames(c("red","blue"),levels(x))
plotTree(simple.tree,type="fan",fsize=0.7,ftype="i",lwd=1)
nodelabels(node=1:simple.tree$Nnode+Ntip(simple.tree),
           pie=fitARD$lik.anc,piecol=cols,cex=0.4)
tiplabels(pie=to.matrix(x[simple.tree$tip.label],levels(x)),
          piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
                  y=0.8*par()$usr[3],fsize=0.8,leg = c("Athero", "No Athero"))

```


2-Ancestral reconstruction with "ER" model 
```{r}
x<-setNames(occurancespecies$Occurance,occurancespecies$Species)

# single-rate model 
fitER<-ace(x,simple.tree,model="ER",type="discrete")
fitER

#plotting ER model on the tree
cols<-setNames(c("red","blue"),levels(x))
plotTree(simple.tree,type="fan",fsize=0.6,ftype="i",lwd=1)
nodelabels(node=1:simple.tree$Nnode+Ntip(simple.tree),
           pie=fitER$lik.anc,piecol=cols,cex=0.4)
tiplabels(pie=to.matrix(x[simple.tree$tip.label],levels(x)),
          piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
                  y=0.8*par()$usr[3],fsize=0.8)
```


3-Ancestral reconstruction with "ARD" model
```{r}
x<-setNames(occurancespecies$Occurance,occurancespecies$Species)
#  model with the backward & forward rates between states are permitted to have different values
fitARD<-ace(x,simple.tree,model="ARD",type="discrete")
fitARD

#plotting ARD model on the tree
# x <- as.character(x)
# x[which(x=="A")] <- "Atherosclerosis"
# x[which(x=="B")] <- "No Atherosclerosis"
# x <- as.factor(x)
cols<-setNames(c("red","blue"),levels(x))
plotTree(simple.tree,type="fan",fsize=0.6,ftype="i",lwd=1)
nodelabels(node=1:simple.tree$Nnode+Ntip(simple.tree),
           pie=fitARD$lik.anc,piecol=cols,cex=0.4)
tiplabels(pie=to.matrix(x[simple.tree$tip.label],levels(x)),
          piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
                  y=0.8*par()$usr[3],fsize=0.8,leg = c("Athero", "No Athero"))


```



4-Ancestral reconstruction with ""
```{r}
#plotting 100 stochastic character maps from our dataset:
mtrees<-make.simmap(tree = simple.tree,x,model="ER",nsim=100)
```

